
name: SACMovieLens_DJ
use_wandb: True

experiment:
  top_k: 10
  data_path: "./row_data/MovieLens/train_df.csv"
  test_data_path: "./row_data/MovieLens/test_df.csv"
  col_mapping:
    user_col_name: "user_idx"
    item_col_name: "item_idx"
    reward_col_name: "relevance"
    timestamp_col_name: "timestamp"

  mdp_settings:
    framestack_size: 10
    reward_function: "condition_reward"
    action_function: "continuous_relevance_action"
    history_keys: ['framestack', 'user_id']

    mdp_type: FullUserHistoryBasedRecSysMDP

  scorer:
    metrics: ['rating_scorer', 'tsne']
    tresh: [0.7, 0.5, 0.9]
    prediction: "continious"

  algo_settings:
    algo: CQL
    n_epochs: 150
    batch_size: 1024
    use_gpu: True

    model_parametrs:
      user_num: 751
      item_num: 1616
      emb_dim: 8
      hid_dim: 16
      memory_size: 10
      feature_size: 256
