# runner type tag
_type_: test.next_item
# wandb project
project: recsys.synth.mdp.next_item_test_scores
# wandb logging
log: True

seed: 42
cuda_device: ...

pipeline: $_base.pipeline_setups.single_epoch
phases: phase_setups.full

env:
  _base_: $_base.env
  n_users: 100
  n_items: 200
  max_rating: 5
  max_episode_len: [120, 50]
  embeddings:
    n_dims: 12
    users: $_base.embeddings.20_clusters_for_12_dims
    items: $_base.embeddings.50_clusters_for_12_dims
  user_state:
    _base_: $_base.user_states.default
    base_satiation_speed: [0.05, .25]
    satiation_drift: 1.0
    relevance_boosting: [0.4, 4.0]
    discrete_actions:
      - [0.2, 0.08]
      - [0.37, 0.1]
      - [0.58, 0.03]
      - [0.75, 0.05]
  dummy:
    item_id: ???
    rating: [.5, 6]

framestack:
  size: 10
  keys:
    - user_id
    - item_ids
    - ratings

embeddings:
  _type_: data.embeddings
  n_dims: 16
  n_users: ???
  n_items: ???
  init_with_als: False
  learn: True

state_encoder:
  output_dim: 512
  hidden_dim: 256
  state_encoding_method: concat
  attention_hidden_dim: 32

mdp:
  reward: one
  action: item
  episode: pause

generation_model: models.discrete_random
eval_model: models.discrete_cql

scoring:
  top_k: 10
  metrics:
    - ndcg
    - stat_hitrate
    - PC
    - ihitrate

wandb_init:
  _base_: $_base.wandb_init
cache:
  cache_root: cache
  enable: ???
  experiment_config: ???
  keep_last_n_experiments: 10

models:
  discrete_random:
    _base_: $_base.models.discrete_random
  informed_random:
    _base_: $_base.models.informed_random
  discrete_bc:
    _base_: $_base.models.discrete_bc
  discrete_cql:
    _base_: $_base.models.discrete_cql
  discrete_sac:
    _base_: $_base.models.discrete_sac
  sdac:
    _base_: $_base.models.sdac

  # ORACLES
  oracle_best:
    _base_: informed_random
    kth_best: 1
  oracle_25:
    _base_: informed_random
    kth_best: .25
  oracle_50:
    _base_: informed_random
    kth_best: .5
  oracle_75:
    _base_: informed_random
    kth_best: .75
  oracle_100:
    _base_: informed_random
    kth_best: .100

phase_setups:
  small:
    generation: $_base.generation_phase_setups.small
    learning: $_base.learning_phase_setups.small
    evaluation: $_base.evaluation_phase_setups.small
  full:
    generation: $_base.generation_phase_setups.full
    learning: $_base.learning_phase_setups.full
    evaluation: $_base.evaluation_phase_setups.full
  half:
    generation: $_base.generation_phase_setups.half
    learning: $_base.learning_phase_setups.full
    evaluation: $_base.evaluation_phase_setups.full
