# runner type tag
_type_: test.next_item
# wandb project
project: recsys.synth.mdp.next_item_test_scores
# wandb logging
log: True

seed: 42
cuda_device: ...

generation_phase:
  epochs: 1
  episodes_per_epoch: 1000
  samples_per_epoch: 10000
  use_cache: true
  switch_to_eval_model: true

learning_phase:
  epochs: 150
  eval_schedule: 5
  eval_episodes: 10
  eval_episodes_all: 40
  eval_users: [0, 1, 2]
  reinitialize: true

env:
  _base_: $_base.env
  n_users: 100
  n_items: 1000
  max_episode_len: [120, 50]
  embeddings:
    n_dims: 8
    users: $_base.embeddings.10_clusters_for_8_dims
    items: $_base.embeddings.20_clusters_for_8_dims
  user_state:
    _base_: $_base.user_states.default
    base_satiation_speed: [0.1, .4]
    satiation_drift: 1.0
    relevance_boosting: [0.2, 4.0]
    discrete_actions:
      - [0.2, 0.08]
      - [0.37, 0.1]
      - [0.58, 0.03]
      - [0.75, 0.05]

framestack:
  size: 10
  empty_rating: [.37, 3]
#  keys: # item|items...

embeddings:
  _type_: data.embeddings
  init_with_als: false
  size: 16

hidden_state_encoder:
#  embedding_dim: ???
  hidden_dim: 256
  memory_size: 10
  feature_size: 512
  #drr adrr
  state_repr_name: full_history
  freeze_emb: False
  attention_hidden_size: 32
  state_keys:
    - item
#    - score
    - user

mdp:
  reward: one
  action: item
  episode: pause

generation_model:
  _base_: $_base.models.discrete_random
  batch_size: 32

eval_model:
  _base_: $_base.models.discrete_cql
  batch_size: 1024

scoring:
  top_k: 10
  metrics: [ndcg, stat_hitrate, PC, ihitrate]

wandb_init: $_base.wandb_init
cache:
  cache_root: cache
  enable: ???
  experiment_config: ???
  keep_last_n_experiments: 4
