# runner type tag
_type_: test.next_item
# wandb project
project: recsys.synth.mdp.next_item_test_scores
# wandb logging
log: True

seed: 42
cuda_device: ...

pipeline: $_base.pipeline_setups.single_epoch
phases: phase_setups.full

env:
  _base_: env_setups.small

framestack:
  size: 10
  keys:
    - user_id
    - item_ids
    - ratings

embeddings:
  _base_: $_base.learned_data_embeddings
  n_dims: 16
  init_with_als: False
  learn: True

state_encoder:
  output_dim: 512
  hidden_dim: 256
  state_encoding_method: concat
  attention_hidden_dim: 32

mdp:
  reward: one
  action: item
  episode: pause

generation_model: models.discrete_random
eval_model: models.discrete_cql

scoring:
  top_k: 10
  metrics:
    - ndcg
    - stat_hitrate
    - PC
    - ihitrate

models:
  discrete_random:
    _base_: $_base.models.discrete_random
  informed_random:
    _base_: $_base.models.informed_random
  discrete_bc:
    _base_: $_base.models.discrete_bc
  discrete_cql:
    _base_: $_base.models.discrete_cql
  discrete_sac:
    _base_: $_base.models.discrete_sac
  sdac:
    _base_: $_base.models.sdac

  # ORACLES
  oracle_confident_best:
    _base_: informed_random
    n_samples: 2.5
    kth_best: 1
  oracle_best:
    _base_: informed_random
    kth_best: 1
    n_samples: 1.4
  oracle_10:
    _base_: informed_random
    kth_best: .1
    n_samples: 1.2
  oracle_25:
    _base_: informed_random
    kth_best: .25
  oracle_50:
    _base_: informed_random
    kth_best: .5
  oracle_75:
    _base_: informed_random
    kth_best: .75
  oracle_90:
    _base_: informed_random
    kth_best: .9
    n_samples: 1.2

env_setups:
  small_8:
    _base_: $_base.envs.small
    embeddings:
      _base_: $_base.env_embeddings_pair
      n_dims: 8
      users: $_base.env_embeddings.10_clusters_for_8_dims
      items: $_base.env_embeddings.20_clusters_for_8_dims
    user_state:
      _base_: user_state.current
  small_12:
    _base_: $_base.envs.small
    embeddings:
      n_dims: 12
      users: $_base.env_embeddings.10_clusters_for_12_dims
      items: $_base.env_embeddings.50_clusters_for_12_dims
    user_state:
      _base_: user_state.current
  mid_12:
    _base_: $_base.envs.mid
    embeddings:
      _base_: $_base.env_embeddings_pair
      n_dims: 12
      users: $_base.env_embeddings.20_clusters_for_12_dims
      items: $_base.env_embeddings.50_clusters_for_12_dims
    user_state: user_state.current
  big_12:
    _base_: $_base.envs.mid
    embeddings:
      _base_: $_base.env_embeddings_pair
      n_dims: 12
      users: $_base.env_embeddings.50_clusters_for_12_dims
      items: $_base.env_embeddings.100_clusters_for_12_dims
    user_state: user_state.current

user_state:
  current:
    _base_: $_base.user_states.static

phase_setups:
  small:
    generation: $_base.generation_phase_setups.small
    learning: $_base.learning_phase_setups.small
    evaluation: $_base.evaluation_phase_setups.small
  full:
    generation: $_base.generation_phase_setups.full
    learning: $_base.learning_phase_setups.full
    evaluation: $_base.evaluation_phase_setups.full
  half:
    generation: $_base.generation_phase_setups.half
    learning: $_base.learning_phase_setups.full
    evaluation: $_base.evaluation_phase_setups.full

wandb_init:
  _base_: $_base.wandb_init

cache:
  cache_root: cache
  enable: ???
  experiment_config: ???
  keep_last_n_experiments: 10
