name: recsys.eval_on_cases
group_name: DCQL_pure_best
seed: 42
use_wandb: true
eval_online: true
env_path: environments/general_env
looking_for: 0,1,6

experiment:
  top_k: 10
  data_path: environments/general_env/train_data.csv
  test_data_path: environments/general_env/test_data.csv
  ratings_column: relevance_int
  mdp_settings:
    framestack_size: 10
    reward_function_name: relevance_based_reward
    action_function_name: next_item_action
    episode_splitter_name: full_user_interaction
    history_keys:
      - framestack
      - user_id
  scorer:
    metrics:
      - ndcg
      - PC
      - ihitrate
      - stat_hitrate
    tresh: '[0.5, 0.7]'
    prediction_type: discrete
  algo_settings:
    n_epochs: 300
    general_parametrs:
      algo: DCQL
      batch_size: 1024
      use_gpu: false
    model_parametrs:
      use_als: false
      user_num: 100
      item_num: 100
      emb_dim: 5
      hid_dim: 256
      memory_size: 10
      feature_size: 512
      state_repr_name: full_history
      freeze_emb: false
      attention_hidden_size: 32
