
name: DSAC_SberZvuk2
use_wandb: True

experiment:
  top_k: 10
  data_path: "./row_data/sbermusic/more_train_df.csv"
  test_data_path: "./row_data/sbermusic/more_test_df.csv"
  col_mapping:
    user_col_name: "user_idx"
    item_col_name: "item_idx"
    reward_col_name: "relevance"
    timestamp_col_name: "timestamp"

  mdp_settings:
    framestack_size: 10
    reward_function_name: "relevance_based_reward"
    action_function_name: "next_item_action"
    episode_splitter_name: "interaction_interruption"
    history_keys: ['framestack', 'user_id']


  scorer:
    metrics: ['ndcg', 'ihitrate', 'coverage', 'stat_hitrate','tsne', 'items_distribution']
    tresh: [0.7, 0.5, 0.9]
    prediction_type: "discrete"

  algo_settings:
    n_epochs: 150

    general_parametrs:
      algo: DCQL
      batch_size: 1024
      use_gpu: False

    model_parametrs:
      use_als: False
      user_num: 1000
      item_num: 2000
      emb_dim: 16
      hid_dim: 32
      memory_size: 10
      feature_size: 512
      use_attention: False
      freeze_emb: False
      attention_hidden_size: 32
