
name: DSAC_SberZvuk
use_wandb: True

experiment:
  top_k: 10
  data_path: "./row_data/sbermusic/more_train_df.csv"
  test_data_path: "./row_data/sbermusic/more_test_df.csv"
  col_mapping:
    user_col_name: "user_idx"
    item_col_name: "item_idx"
    reward_col_name: "relevance"
    timestamp_col_name: "timestamp"

  mdp_settings:
    framestack_size: 20
    reward_function: "relevance_based_reward"
    action_function: "next_item_action"
    history_keys: ['framestack', 'user_id']

    mdp_type: ConditionBasedRecSysMDP

  scorer:
    metrics: ['hit_rate', 'coverage']
    tresh: [0.7, 0.5, 0.9]
    prediction: "discrete"

  algo_settings:
    algo: DBC
    n_epochs: 1500
    batch_size: 1024
    use_gpu: False
    use_als: False
   #1000 1000 32 64 20 256 1 64
    model_parametrs:
      user_num: 1000
      item_num: 1000
      emb_dim: 32
      hid_dim: 64
      memory_size: 20
      feature_size: 256
      use_attention: True
      freeze_emb: False
      attention_hidden_size: 64
